/* Backward-compatibility checks - docs/spec/03-state-contract.md#older-save-files-keep-working
 *
 * Everything here runs against tests/fixtures/save-5.0.0-pre-autocast.js, a real save captured
 * out of an earlier build rather than generated by this one. That is what separates these
 * checks from the ones in save.test.js: those prove the engine can read what it just wrote,
 * which it always can. These prove it can still read what a *previous* build wrote, which is
 * the thing that actually breaks - the game has an export button, so save files are on
 * players' disks and outlive every build after them.
 *
 * They assert properties, not a snapshot. A golden-file comparison would fail on every
 * legitimate field addition and be re-blessed without being read, which costs maintenance and
 * catches nothing. */

(function () {
  const { engine, test, assert, assertEqual, advance, fakeClock, seededRng } = typeof require === "function"
    ? require("./harness.js")
    : window.SpiritTests;

  const FIXTURE = typeof require === "function"
    ? require("./fixtures/save-5.0.0-pre-autocast.js")
    : window.SpiritSaveFixtures.pre500AutoCast;

  /* The fixture is shared by every check below and migrateSave normalizes in place, so each
   * one gets its own copy. Through JSON rather than a spread: that is what a real load does to
   * it, and a shallow copy would leave every nested object shared. */
  function oldSave() {
    return JSON.parse(JSON.stringify(FIXTURE));
  }

  /* The clock is injected, so pin it - migrateSave stamps log lines, and a reset writes one. */
  function pinClock() {
    const clock = fakeClock();
    engine.setNowSource(clock.now);
    engine.setRng(seededRng(42));
    return clock;
  }

  test("compat: a save from an earlier build loads without being wiped", () => {
    pinClock();
    const migrated = engine.migrateSave(oldSave());

    assertEqual(migrated.reset, false, "an older 5.0.0 save must not hit the hard-reset path");
    assertEqual(migrated.state.schemaVersion, engine.VERSION, "loads as the current version");
  });

  test("compat: an older save keeps what the player earned", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());

    assertEqual(state.meta.fear, 4820, "fear");
    assertEqual(state.meta.bestWaveReached, 11, "best wave");
  });

  test("compat: an older save keeps every purchase, snapshot included", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());

    assertEqual(state.upgrades.purchased.dahan_remember, 2, "a laddered upgrade keeps its tier");
    assertEqual(state.upgrades.purchased.auto_wash_away, 1, "a one-off automation is still owned");
    assertEqual(state.upgrades.purchased.auto_start_round, 1, "the round automation is still owned");
    // The round's frozen copy is a separate field and is normalized separately: a save loaded
    // mid-round has to resume the round it was in, not one playing by a different snapshot.
    assertEqual(engine.activeUpgradeTier(state, "dahan_remember"), 2, "the round's snapshot agrees");
  });

  /* Grandfathering, against a save actually captured from the build that predates ascension.
   *
   * This fixture owns `auto_start_round`, bought for 500 Fear under the old completion gate.
   * The change put that row behind a currency the save has none of, so without the grant on
   * load the player would open the game to find a purchase they had made taken away and a
   * price in Presence they cannot pay. The grant is what makes the change additive rather than
   * a quiet confiscation. */
  test("compat: an older save's automations bring their Presence unlocks with them", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());

    assert(
      engine.presenceUpgradeOwned(state, "presence_tide_returns"),
      "the Presence row that now opens auto_start_round is granted"
    );
    assert(
      !engine.upgradeNeedsPresence(state, "auto_start_round"),
      "so the row it owns is not locked out from under it"
    );
    assertEqual(state.meta.presence, 0, "and the grant is the row itself, never spendable Presence");
  });

  // The layer is additive: a save written before it existed has ascended zero times and holds
  // no Presence, and nothing about it may be inferred from what the save did have.
  test("compat: an older save starts the ascension layer at zero", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());

    assertEqual(state.meta.presence, 0, "no Presence");
    assertEqual(state.meta.ascensionCount, 0, "no ascensions");
    assertEqual(state.meta.cycleBestWave, 0, "and no cycle best, despite a best wave of 11");
    assertEqual(state.meta.bestWaveReached, 11, "which the all-time record keeps");
  });

  test("compat: an older save keeps the preferences it carries", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());

    assertEqual(state.ui.language, "en", "language");
    assertEqual(state.ui.autoProceed, true, "auto-proceed");
    assertEqual(state.ui.autoStartRound, true, "auto-start-round");
  });

  /* The check that does not need editing when the next field lands. It reads the fresh state's
   * own ui keys, so a field added tomorrow is covered the moment createInitialState writes it. */
  test("compat: every ui field added since the file was written loads at its fresh default", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());
    const fresh = engine.createInitialState();
    const raw = FIXTURE.ui;

    for (const key of Object.keys(fresh.ui)) {
      assert(key in state.ui, `ui.${key} is missing from a loaded older save`);
      if (key in raw) continue;
      assertEqual(
        JSON.stringify(state.ui[key]),
        JSON.stringify(fresh.ui[key]),
        `ui.${key} was added after the fixture was written and must load at its fresh default`
      );
    }
  });

  test("compat: the five auto-cast toggles default on for a save that predates them", () => {
    pinClock();
    const { state } = engine.migrateSave(oldSave());

    assert(!("autoCast" in FIXTURE.ui), "the fixture must predate ui.autoCast or this proves nothing");
    for (const abilityId of Object.keys(engine.AUTO_CAST_UPGRADES)) {
      assertEqual(state.ui.autoCast[abilityId], true, `${abilityId} defaults on`);
    }
  });

  /* Loading is only half of it. A save that comes back in a shape tick throws on is not
   * compatible, and the reset check above would not notice. */
  test("compat: a save from an earlier build is still playable", () => {
    const clock = pinClock();
    const { state } = engine.migrateSave(oldSave());
    const ctx = { state, clock };

    engine.startRound(state);
    // Opened by hand, exactly as newGame does it: startRound closes the gate on the shipped
    // default, and a round held behind "waiting" would run no waves and prove nothing here.
    state.round.awaitingWave = false;
    const headBefore = state._log[0];
    advance(ctx, engine.WAVE_INTERVAL_SECONDS + 1);

    assertEqual(state.round.status, "running", "the round survives a wave");
    assertEqual(state.round.wavesResolved, 1, "and actually resolved one");
    assert(state._log[0] !== headBefore, "the wave wrote something to the log");
  });

  test("compat: an older save survives the export/import path the player uses", () => {
    pinClock();
    const loaded = engine.migrateSave(oldSave()).state;
    const imported = engine.importSave(engine.exportSave(loaded));

    assertEqual(imported.ok, true, "the file imports");
    assertEqual(imported.reset, false, "and is not wiped on the way in");
    assertEqual(imported.state.meta.fear, 4820, "fear survives the round-trip");
  });

  /* The guard the seven above do not give. Compatibility is not "never reset" - it is "reset
   * only when the shape genuinely changed" - and a suite that proved only the first half would
   * pass just as happily on an engine that had stopped resetting anything at all. */
  test("compat: a save from a genuinely older schema still resets, and says where from", () => {
    pinClock();
    const ancient = oldSave();
    ancient.schemaVersion = "2.0.0";

    const migrated = engine.migrateSave(ancient);
    assertEqual(migrated.reset, true, "an incompatible schema is reset, not read");
    assertEqual(migrated.fromVersion, "2.0.0", "and names the version it came from");
    assertEqual(migrated.state.meta.fear, 0, "the reset is a real one");
  });
})();
